# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.srcs/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/mpsoc_preset_PL_VICFAR_AXIS_0_0.xci
# IP: The module: 'mpsoc_preset_PL_VICFAR_AXIS_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i0/vicfar1_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i0 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i1/vicfar1_c_addsub_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i1 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i2/vicfar1_c_addsub_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i2 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i3/vicfar1_c_addsub_v12_0_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i3 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i4/vicfar1_c_addsub_v12_0_i4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i4 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i5/vicfar1_c_addsub_v12_0_i5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i5 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i5} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i6/vicfar1_c_addsub_v12_0_i6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i6 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i6} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i7/vicfar1_c_addsub_v12_0_i7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i7 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i7} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i8/vicfar1_c_addsub_v12_0_i8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i8 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i8} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_counter_binary_v12_0_i0/vicfar1_c_counter_binary_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==vicfar1_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i0/vicfar1_div_gen_v5_1_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_div_gen_v5_1_i0 || ORIG_REF_NAME==vicfar1_div_gen_v5_1_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i1/vicfar1_div_gen_v5_1_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_div_gen_v5_1_i1 || ORIG_REF_NAME==vicfar1_div_gen_v5_1_i1} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i2/vicfar1_div_gen_v5_1_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_div_gen_v5_1_i2 || ORIG_REF_NAME==vicfar1_div_gen_v5_1_i2} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i3/vicfar1_div_gen_v5_1_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_div_gen_v5_1_i3 || ORIG_REF_NAME==vicfar1_div_gen_v5_1_i3} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i0/vicfar1_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_mult_gen_v12_0_i0 || ORIG_REF_NAME==vicfar1_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i1/vicfar1_mult_gen_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_mult_gen_v12_0_i1 || ORIG_REF_NAME==vicfar1_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i2/vicfar1_mult_gen_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_mult_gen_v12_0_i2 || ORIG_REF_NAME==vicfar1_mult_gen_v12_0_i2} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i3/vicfar1_mult_gen_v12_0_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_mult_gen_v12_0_i3 || ORIG_REF_NAME==vicfar1_mult_gen_v12_0_i3} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i4/vicfar1_mult_gen_v12_0_i4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_mult_gen_v12_0_i4 || ORIG_REF_NAME==vicfar1_mult_gen_v12_0_i4} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i5/vicfar1_mult_gen_v12_0_i5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_mult_gen_v12_0_i5 || ORIG_REF_NAME==vicfar1_mult_gen_v12_0_i5} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i6/vicfar1_mult_gen_v12_0_i6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_mult_gen_v12_0_i6 || ORIG_REF_NAME==vicfar1_mult_gen_v12_0_i6} -quiet] -quiet

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/constrs/vicfar1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpsoc_preset_PL_VICFAR_AXIS_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.srcs/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/mpsoc_preset_PL_VICFAR_AXIS_0_0.xci
# IP: The module: 'mpsoc_preset_PL_VICFAR_AXIS_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i0/vicfar1_c_addsub_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i0 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i1/vicfar1_c_addsub_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i1 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i2/vicfar1_c_addsub_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i2 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i3/vicfar1_c_addsub_v12_0_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i3 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i4/vicfar1_c_addsub_v12_0_i4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i4 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i5/vicfar1_c_addsub_v12_0_i5.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i5 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i5} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i6/vicfar1_c_addsub_v12_0_i6.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i6 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i6} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i7/vicfar1_c_addsub_v12_0_i7.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i7 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i7} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i8/vicfar1_c_addsub_v12_0_i8.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_addsub_v12_0_i8 || ORIG_REF_NAME==vicfar1_c_addsub_v12_0_i8} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_counter_binary_v12_0_i0/vicfar1_c_counter_binary_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==vicfar1_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i0/vicfar1_div_gen_v5_1_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_div_gen_v5_1_i0 || ORIG_REF_NAME==vicfar1_div_gen_v5_1_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i1/vicfar1_div_gen_v5_1_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_div_gen_v5_1_i1 || ORIG_REF_NAME==vicfar1_div_gen_v5_1_i1} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i2/vicfar1_div_gen_v5_1_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_div_gen_v5_1_i2 || ORIG_REF_NAME==vicfar1_div_gen_v5_1_i2} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i3/vicfar1_div_gen_v5_1_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_div_gen_v5_1_i3 || ORIG_REF_NAME==vicfar1_div_gen_v5_1_i3} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i0/vicfar1_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_mult_gen_v12_0_i0 || ORIG_REF_NAME==vicfar1_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i1/vicfar1_mult_gen_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_mult_gen_v12_0_i1 || ORIG_REF_NAME==vicfar1_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i2/vicfar1_mult_gen_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_mult_gen_v12_0_i2 || ORIG_REF_NAME==vicfar1_mult_gen_v12_0_i2} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i3/vicfar1_mult_gen_v12_0_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_mult_gen_v12_0_i3 || ORIG_REF_NAME==vicfar1_mult_gen_v12_0_i3} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i4/vicfar1_mult_gen_v12_0_i4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_mult_gen_v12_0_i4 || ORIG_REF_NAME==vicfar1_mult_gen_v12_0_i4} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i5/vicfar1_mult_gen_v12_0_i5.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_mult_gen_v12_0_i5 || ORIG_REF_NAME==vicfar1_mult_gen_v12_0_i5} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i6/vicfar1_mult_gen_v12_0_i6.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==vicfar1_mult_gen_v12_0_i6 || ORIG_REF_NAME==vicfar1_mult_gen_v12_0_i6} -quiet] -quiet

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/constrs/vicfar1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpsoc_preset_PL_VICFAR_AXIS_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
