# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.srcs/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_auto_ds_2/mpsoc_preset_auto_ds_2.xci
# IP: The module: 'mpsoc_preset_auto_ds_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_auto_ds_2/mpsoc_preset_auto_ds_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpsoc_preset_auto_ds_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_auto_ds_2/mpsoc_preset_auto_ds_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpsoc_preset_auto_ds_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.srcs/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_auto_ds_2/mpsoc_preset_auto_ds_2.xci
# IP: The module: 'mpsoc_preset_auto_ds_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_auto_ds_2/mpsoc_preset_auto_ds_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpsoc_preset_auto_ds_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_auto_ds_2/mpsoc_preset_auto_ds_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpsoc_preset_auto_ds_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
