# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.srcs/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mpsoc_preset_mft_overlap_add_0_0.xci
# IP: The module: 'mpsoc_preset_mft_overlap_add_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_c_addsub_v12_0_i0/mft_overlap_add_2022_0303_c_addsub_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i0 || ORIG_REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_c_addsub_v12_0_i1/mft_overlap_add_2022_0303_c_addsub_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i1 || ORIG_REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_c_addsub_v12_0_i2/mft_overlap_add_2022_0303_c_addsub_v12_0_i2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i2 || ORIG_REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_c_addsub_v12_0_i3/mft_overlap_add_2022_0303_c_addsub_v12_0_i3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i3 || ORIG_REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_c_addsub_v12_0_i4/mft_overlap_add_2022_0303_c_addsub_v12_0_i4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i4 || ORIG_REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_c_counter_binary_v12_0_i0/mft_overlap_add_2022_0303_c_counter_binary_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==mft_overlap_add_2022_0303_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_cmpy_v6_0_i0/mft_overlap_add_2022_0303_cmpy_v6_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_cmpy_v6_0_i0 || ORIG_REF_NAME==mft_overlap_add_2022_0303_cmpy_v6_0_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_mult_gen_v12_0_i0/mft_overlap_add_2022_0303_mult_gen_v12_0_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_mult_gen_v12_0_i0 || ORIG_REF_NAME==mft_overlap_add_2022_0303_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_mult_gen_v12_0_i1/mft_overlap_add_2022_0303_mult_gen_v12_0_i1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_mult_gen_v12_0_i1 || ORIG_REF_NAME==mft_overlap_add_2022_0303_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_xfft_v9_1_i0/mft_overlap_add_2022_0303_xfft_v9_1_i0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_xfft_v9_1_i0 || ORIG_REF_NAME==mft_overlap_add_2022_0303_xfft_v9_1_i0} -quiet] -quiet

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/constrs/mft_overlap_add_2022_0303.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpsoc_preset_mft_overlap_add_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.srcs/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mpsoc_preset_mft_overlap_add_0_0.xci
# IP: The module: 'mpsoc_preset_mft_overlap_add_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_c_addsub_v12_0_i0/mft_overlap_add_2022_0303_c_addsub_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i0 || ORIG_REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_c_addsub_v12_0_i1/mft_overlap_add_2022_0303_c_addsub_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i1 || ORIG_REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_c_addsub_v12_0_i2/mft_overlap_add_2022_0303_c_addsub_v12_0_i2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i2 || ORIG_REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_c_addsub_v12_0_i3/mft_overlap_add_2022_0303_c_addsub_v12_0_i3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i3 || ORIG_REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_c_addsub_v12_0_i4/mft_overlap_add_2022_0303_c_addsub_v12_0_i4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i4 || ORIG_REF_NAME==mft_overlap_add_2022_0303_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_c_counter_binary_v12_0_i0/mft_overlap_add_2022_0303_c_counter_binary_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_c_counter_binary_v12_0_i0 || ORIG_REF_NAME==mft_overlap_add_2022_0303_c_counter_binary_v12_0_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_cmpy_v6_0_i0/mft_overlap_add_2022_0303_cmpy_v6_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_cmpy_v6_0_i0 || ORIG_REF_NAME==mft_overlap_add_2022_0303_cmpy_v6_0_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_mult_gen_v12_0_i0/mft_overlap_add_2022_0303_mult_gen_v12_0_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_mult_gen_v12_0_i0 || ORIG_REF_NAME==mft_overlap_add_2022_0303_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_mult_gen_v12_0_i1/mft_overlap_add_2022_0303_mult_gen_v12_0_i1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_mult_gen_v12_0_i1 || ORIG_REF_NAME==mft_overlap_add_2022_0303_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mft_overlap_add_2022_0303_xfft_v9_1_i0/mft_overlap_add_2022_0303_xfft_v9_1_i0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mft_overlap_add_2022_0303_xfft_v9_1_i0 || ORIG_REF_NAME==mft_overlap_add_2022_0303_xfft_v9_1_i0} -quiet] -quiet

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/constrs/mft_overlap_add_2022_0303.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpsoc_preset_mft_overlap_add_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
