# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/mpsoc_preset/mpsoc_preset.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset || ORIG_REF_NAME==mpsoc_preset} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_zynq_ultra_ps_e_0_0/mpsoc_preset_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==mpsoc_preset_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_axi_gpio_0_0/mpsoc_preset_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_axi_gpio_0_0 || ORIG_REF_NAME==mpsoc_preset_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_xbar_0/mpsoc_preset_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_xbar_0 || ORIG_REF_NAME==mpsoc_preset_xbar_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_ps8_0_axi_periph_0/mpsoc_preset_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_ps8_0_axi_periph_0 || ORIG_REF_NAME==mpsoc_preset_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_rst_ps8_0_99M_0/mpsoc_preset_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_rst_ps8_0_99M_0 || ORIG_REF_NAME==mpsoc_preset_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_axi_bram_ctrl_0_0/mpsoc_preset_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_axi_bram_ctrl_0_0 || ORIG_REF_NAME==mpsoc_preset_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_axi_bram_ctrl_0_bram_0/mpsoc_preset_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==mpsoc_preset_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/mpsoc_preset_PL_VICFAR_AXIS_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_PL_VICFAR_AXIS_0_0 || ORIG_REF_NAME==mpsoc_preset_PL_VICFAR_AXIS_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_mft_overlap_add_0_0/mpsoc_preset_mft_overlap_add_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_mft_overlap_add_0_0 || ORIG_REF_NAME==mpsoc_preset_mft_overlap_add_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_clk_wiz_0_0/mpsoc_preset_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_clk_wiz_0_0 || ORIG_REF_NAME==mpsoc_preset_clk_wiz_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_proc_sys_reset_0_0/mpsoc_preset_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_proc_sys_reset_0_0 || ORIG_REF_NAME==mpsoc_preset_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_fifo_generator_0_0/mpsoc_preset_fifo_generator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_fifo_generator_0_0 || ORIG_REF_NAME==mpsoc_preset_fifo_generator_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_FDRE_0_0/mpsoc_preset_FDRE_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_FDRE_0_0 || ORIG_REF_NAME==mpsoc_preset_FDRE_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_PL_IO_TriggerCtrl_v1_0_0/mpsoc_preset_PL_IO_TriggerCtrl_v1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_PL_IO_TriggerCtrl_v1_0_0 || ORIG_REF_NAME==mpsoc_preset_PL_IO_TriggerCtrl_v1_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_PL_SPI_ADC_MasterStr_0_0/mpsoc_preset_PL_SPI_ADC_MasterStr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_PL_SPI_ADC_MasterStr_0_0 || ORIG_REF_NAME==mpsoc_preset_PL_SPI_ADC_MasterStr_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_axis_subset_converter_0_0/mpsoc_preset_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_axis_subset_converter_0_0 || ORIG_REF_NAME==mpsoc_preset_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/mpsoc_preset_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_system_ila_0_0 || ORIG_REF_NAME==mpsoc_preset_system_ila_0_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_auto_ds_0/mpsoc_preset_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_auto_ds_0 || ORIG_REF_NAME==mpsoc_preset_auto_ds_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_auto_pc_0/mpsoc_preset_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_auto_pc_0 || ORIG_REF_NAME==mpsoc_preset_auto_pc_0} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_auto_ds_1/mpsoc_preset_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_auto_ds_1 || ORIG_REF_NAME==mpsoc_preset_auto_ds_1} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_auto_ds_2/mpsoc_preset_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_auto_ds_2 || ORIG_REF_NAME==mpsoc_preset_auto_ds_2} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_auto_pc_1/mpsoc_preset_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_auto_pc_1 || ORIG_REF_NAME==mpsoc_preset_auto_pc_1} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_auto_ds_3/mpsoc_preset_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_auto_ds_3 || ORIG_REF_NAME==mpsoc_preset_auto_ds_3} -quiet] -quiet

# IP: bd/mpsoc_preset/ip/mpsoc_preset_auto_pc_2/mpsoc_preset_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mpsoc_preset_auto_pc_2 || ORIG_REF_NAME==mpsoc_preset_auto_pc_2} -quiet] -quiet

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/mpsoc_preset_ooc.xdc
