# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.srcs/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_axi_bram_ctrl_0_0/mpsoc_preset_axi_bram_ctrl_0_0.xci
# IP: The module: 'mpsoc_preset_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_axi_bram_ctrl_0_0/mpsoc_preset_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpsoc_preset_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.srcs/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_axi_bram_ctrl_0_0/mpsoc_preset_axi_bram_ctrl_0_0.xci
# IP: The module: 'mpsoc_preset_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_axi_bram_ctrl_0_0/mpsoc_preset_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpsoc_preset_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
