# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.runs/mpsoc_preset_PL_VICFAR_AXIS_0_0_synth_1/.Xil/Vivado-27828-DESKTOP-L5VUIVN/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xczu9eg-ffvb1156-2-e
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ipshared/dcfb/hdl {
      D:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      D:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ipshared/dcfb/hdl {
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ipshared/dcfb/hdl/synth_reg.v
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ipshared/dcfb/hdl/synth_reg_w_init.v
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ipshared/dcfb/hdl/convert_type.v
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ipshared/dcfb/hdl/xlclockdriver_rd.v
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ipshared/dcfb/hdl/vicfar1_entity_declarations.v
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ipshared/dcfb/hdl/vicfar1.v
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/synth/mpsoc_preset_PL_VICFAR_AXIS_0_0.v
    }
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib xbip_utils_v3_0_10 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i6/hdl/xbip_utils_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_pipe_v3_0_6 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i6/hdl/xbip_pipe_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_bram18k_v3_0_6 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i6/hdl/xbip_bram18k_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib mult_gen_v12_0_18 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i6/hdl/mult_gen_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i6/synth/vicfar1_mult_gen_v12_0_i6.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i5/synth/vicfar1_mult_gen_v12_0_i5.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i4/synth/vicfar1_mult_gen_v12_0_i4.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i3/synth/vicfar1_mult_gen_v12_0_i3.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i2/synth/vicfar1_mult_gen_v12_0_i2.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i1/synth/vicfar1_mult_gen_v12_0_i1.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_mult_gen_v12_0_i0/synth/vicfar1_mult_gen_v12_0_i0.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i3/synth/vicfar1_div_gen_v5_1_i3.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i2/synth/vicfar1_div_gen_v5_1_i2.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i1/synth/vicfar1_div_gen_v5_1_i1.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i0/synth/vicfar1_div_gen_v5_1_i0.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_counter_binary_v12_0_i0/synth/vicfar1_c_counter_binary_v12_0_i0.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i8/synth/vicfar1_c_addsub_v12_0_i8.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i7/synth/vicfar1_c_addsub_v12_0_i7.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i6/synth/vicfar1_c_addsub_v12_0_i6.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i5/synth/vicfar1_c_addsub_v12_0_i5.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i4/synth/vicfar1_c_addsub_v12_0_i4.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i3/synth/vicfar1_c_addsub_v12_0_i3.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i2/synth/vicfar1_c_addsub_v12_0_i2.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i1/synth/vicfar1_c_addsub_v12_0_i1.vhd
      c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_addsub_v12_0_i0/synth/vicfar1_c_addsub_v12_0_i0.vhd
    }
      rt::read_vhdl -lib axi_utils_v2_0_6 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i3/hdl/axi_utils_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_wrapper_v3_0_4 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i3/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_addsub_v3_0_6 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i3/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib floating_point_v7_0_20 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i3/hdl/floating_point_v7_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_mult_v3_0_6 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i3/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_multadd_v3_0_6 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i3/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib div_gen_v5_1_19 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_div_gen_v5_1_i3/hdl/div_gen_v5_1_vh_rfs.vhd
      rt::read_vhdl -lib c_reg_fd_v12_0_6 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_counter_binary_v12_0_i0/hdl/c_reg_fd_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_addsub_v3_0_6 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_counter_binary_v12_0_i0/hdl/xbip_addsub_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib c_addsub_v12_0_14 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_counter_binary_v12_0_i0/hdl/c_addsub_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib c_gate_bit_v12_0_6 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_counter_binary_v12_0_i0/hdl/c_gate_bit_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_counter_v3_0_6 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_counter_binary_v12_0_i0/hdl/xbip_counter_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib c_counter_binary_v12_0_15 c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_PL_VICFAR_AXIS_0_0/vicfar1_c_counter_binary_v12_0_i0/hdl/c_counter_binary_v12_0_vh_rfs.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top mpsoc_preset_PL_VICFAR_AXIS_0_0
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.runs/mpsoc_preset_PL_VICFAR_AXIS_0_0_synth_1/.Xil/Vivado-27828-DESKTOP-L5VUIVN/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
