# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.srcs/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/mpsoc_preset_system_ila_0_0.xci
# IP: The module: 'mpsoc_preset_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/bd_9390.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9390 || ORIG_REF_NAME==bd_9390} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/ip/ip_0/bd_9390_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9390_ila_lib_0 || ORIG_REF_NAME==bd_9390_ila_lib_0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/ip/ip_1/bd_9390_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9390_g_inst_0 || ORIG_REF_NAME==bd_9390_g_inst_0} -quiet] -quiet

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9390_ila_lib_0 || ORIG_REF_NAME==bd_9390_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9390_ila_lib_0 || ORIG_REF_NAME==bd_9390_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/ip/ip_0/bd_9390_ila_lib_0_ooc.xdc

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/bd_9390_ooc.xdc

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/mpsoc_preset_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpsoc_preset_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.srcs/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/mpsoc_preset_system_ila_0_0.xci
# IP: The module: 'mpsoc_preset_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/bd_9390.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9390 || ORIG_REF_NAME==bd_9390} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/ip/ip_0/bd_9390_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9390_ila_lib_0 || ORIG_REF_NAME==bd_9390_ila_lib_0} -quiet] -quiet

# IP: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/ip/ip_1/bd_9390_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9390_g_inst_0 || ORIG_REF_NAME==bd_9390_g_inst_0} -quiet] -quiet

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9390_ila_lib_0 || ORIG_REF_NAME==bd_9390_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9390_ila_lib_0 || ORIG_REF_NAME==bd_9390_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/ip/ip_0/bd_9390_ila_lib_0_ooc.xdc

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/bd_0/bd_9390_ooc.xdc

# XDC: c:/Users/SKLTMW05/workspace/zc102_detection/zc102_detection.gen/sources_1/bd/mpsoc_preset/ip/mpsoc_preset_system_ila_0_0/mpsoc_preset_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mpsoc_preset_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
